# Generated by Django 2.2.1 on 2019-08-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
    ]
